apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-network-policy
  labels:
    app.kubernetes.io/component: web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: mail
  policyTypes:
    - Ingress
  ingress:
    # Allow all pod-to-pod communication within the namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 9000 # PHP-FPM
        - protocol: TCP
          port: 8080 # HTTP
    # Allow ingress from ingress-nginx namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
