apiVersion: v1
kind: Service
metadata:
  name: mta
  labels:
    app.kubernetes.io/name: mta
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: docker-mailserver
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: smtp
    - name: submission
      port: 587
      protocol: TCP
      targetPort: submission
  selector:
    app.kubernetes.io/name: mta
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: docker-mailserver
