---
services:
  mailpit:
    image: axllent/mailpit:v1.27@sha256:fb84cfb1c3a33007cfdee8ba5a77b8c6c894de5b1a368372ddc5c965cf5c0b6d

  fetchmail:
    links:
      - mda:mda.local

  test:
    build: ./test
    volumes:
      - data-mail:/var/vmail:ro
      - data-tls:/media/tls:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For development
      - ./test/rootfs/usr/share/tests:/usr/share/tests:ro
    env_file: .env
    depends_on:
      - mailpit
      - fetchmail

  # For development
  # web:
  #   volumes:
  #     - ./web/rootfs/etc/nginx/nginx.conf.templ:/etc/nginx/nginx.conf.templ:ro
  #   ports:
  #     - "0.0.0.0:81:80"
