apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: mail
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: mail
