sql_driver = mysql

mysql default {
  host = $ENV:DB_HOST
  port = $ENV:DB_PORT
  user = $ENV:DB_USER
  password = $ENV:DB_PASSWORD
  dbname = $ENV:DB_NAME
  option_file = /etc/my.cnf
  option_group = client
}
