apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unbound-network-policy
  labels:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/component: dns
    app.kubernetes.io/part-of: docker-mailserver
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: unbound
      app.kubernetes.io/component: dns
      app.kubernetes.io/part-of: docker-mailserver
  policyTypes:
    - Ingress
  ingress:
    # Allow all pod-to-pod communication within the namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: UDP
          port: 53 # DNS
        - protocol: TCP
          port: 53 # DNS TCP
