apiVersion: v1
kind: Service
metadata:
  name: unbound
  labels:
    app.kubernetes.io/component: unbound
    app.kubernetes.io/instance: mail
spec:
  type: ClusterIP
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: dns
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  selector:
    app.kubernetes.io/component: unbound
    app.kubernetes.io/instance: mail
