---

MD004: false                  # Unordered list style
MD003: false                  # Header style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far too short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD034: false                  # Bare URL used
MD036: false                  # Emphasis used instead of a heading
MD051: false                  # Link fragments

blank_lines: false            # Error on blank lines
