---
services:
  redis:
    image: redis:8.2-alpine
    restart: on-failure:5
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    env_file: ../../.env
    volumes:
      - data-redis:/data
