{{- if .Values.mta.service.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-mailserver.mta" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mta
  {{- if or .Values.commonAnnotations .Values.mta.service.annotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.mta.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mta.service.type }}
  {{- if and .Values.mta.service.clusterIP (eq .Values.mta.service.type "ClusterIP") }}
  clusterIP: {{ .Values.mta.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.mta.service.type "LoadBalancer") (eq .Values.mta.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.mta.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.mta.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.mta.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.mta.service.type "LoadBalancer") (not (empty .Values.mta.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.mta.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.mta.service.sessionAffinity }}
  sessionAffinity: {{ .Values.mta.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.mta.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.mta.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: smtp
      port: {{ coalesce .Values.mta.service.port .Values.mta.service.ports.smtp }}
      targetPort: 25
      protocol: TCP
      {{- if (and (or (eq .Values.mta.service.type "NodePort") (eq .Values.mta.service.type "LoadBalancer")) (not (empty (coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.smtp)))) }}
      nodePort: {{ coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.smtp }}
      {{- else if eq .Values.mta.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: submission
      port: {{ coalesce .Values.mta.service.port .Values.mta.service.ports.submission }}
      targetPort: 587
      protocol: TCP
      {{- if (and (or (eq .Values.mta.service.type "NodePort") (eq .Values.mta.service.type "LoadBalancer")) (not (empty (coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.submission)))) }}
      nodePort: {{ coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.submission }}
      {{- else if eq .Values.mta.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: submissionssl
      port: {{ coalesce .Values.mta.service.port .Values.mta.service.ports.submissionssl }}
      targetPort: 465
      protocol: TCP
      {{- if (and (or (eq .Values.mta.service.type "NodePort") (eq .Values.mta.service.type "LoadBalancer")) (not (empty (coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.submissionssl)))) }}
      nodePort: {{ coalesce .Values.mta.service.nodePort .Values.mta.service.nodePorts.submissionssl }}
      {{- else if eq .Values.mta.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.mta.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.mta.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.mta.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mta
{{- end }}
