---

{{- if.Values.config.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-domain: {{ .Values.config.admin.domain | b64enc | quote }}
  admin-name: {{ .Values.config.admin.name | b64enc | quote }}
  admin-password: {{ .Values.config.admin.password | b64enc | quote }}
{{- end }}
