---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-mailserver.mta" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mta
  {{- if or .Values.commonAnnotations .Values.mta.internalService.annotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.mta.internalService.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mta.internalService.type }}
  {{- if and .Values.mta.internalService.clusterIP (eq .Values.mta.internalService.type "ClusterIP") }}
  clusterIP: {{ .Values.mta.internalService.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.mta.internalService.type "LoadBalancer") (eq .Values.mta.internalService.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.mta.internalService.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.mta.internalService.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.mta.internalService.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.mta.internalService.type "LoadBalancer") (not (empty .Values.mta.internalService.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.mta.internalService.loadBalancerIP }}
  {{- end }}
  {{- if .Values.mta.internalService.sessionAffinity }}
  sessionAffinity: {{ .Values.mta.internalService.sessionAffinity }}
  {{- end }}
  {{- if .Values.mta.internalService.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.mta.internalService.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: smtp
      port: {{ coalesce .Values.mta.internalService.port .Values.mta.internalService.ports.smtp }}
      targetPort: 25
      protocol: TCP
      {{- if (and (or (eq .Values.mta.internalService.type "NodePort") (eq .Values.mta.internalService.type "LoadBalancer")) (not (empty (coalesce .Values.mta.internalService.nodePort .Values.mta.internalService.nodePorts.smtp)))) }}
      nodePort: {{ coalesce .Values.mta.internalService.nodePort .Values.mta.internalService.nodePorts.smtp }}
      {{- else if eq .Values.mta.internalService.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.mta.internalService.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.mta.internalService.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.mta.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mta
