<?php

$config['password_driver'] = 'sql';
$config['password_confirm_current'] = true;
$config['password_minimum_length'] = 6;
$config['password_require_nonalpha'] = false;
$config['password_log'] = false;
$config['password_login_exceptions'] = null;
$config['password_hosts'] = null;
$config['password_force_save'] = true;
$config['password_force_new_user'] = false;
$config['password_algorithm'] = 'clear';
$config['password_algorithm_prefix'] = '';
$config['password_dovecotpw'] = '/usr/local/sbin/dovecotpw'; // for dovecot-1.x
$config['password_dovecotpw_method'] = 'CRAM-MD5';
$config['password_blowfish_cost'] = 12;
$config['password_disabled'] = false;
$config['password_db_dsn'] = sprintf('mysql://%s:%s@%s/%s', getenv('MYSQL_USER'), getenv('MYSQL_PASSWORD'), getenv('MYSQL_HOST'), getenv('MYSQL_DATABASE'));
$config['password_query'] = "UPDATE virtual_users SET password=CONCAT('{SHA256-CRYPT}', ENCRYPT (%p, CONCAT('$5$', SUBSTRING(SHA(RAND()), -16)))) WHERE email=%u;";
$config['password_crypt_hash'] = 'md5';
$config['password_idn_ascii'] = false;
$config['password_dovecotpw_with_method'] = false;
$config['password_hash_algorithm'] = 'sha1';
$config['password_hash_base64'] = false;
$config['password_pop_host'] = 'localhost';
$config['password_pop_port'] = 106;
$config['password_saslpasswd_args'] = '';
$config['password_ldap_host'] = 'localhost';
$config['password_ldap_port'] = '389';
$config['password_ldap_starttls'] = false;
$config['password_ldap_version'] = '3';
$config['password_ldap_basedn'] = 'dc=exemple,dc=com';
$config['password_ldap_method'] = 'user';
$config['password_ldap_adminDN'] = null;
$config['password_ldap_adminPW'] = null;
$config['password_ldap_userDN_mask'] = 'uid=%login,ou=people,dc=exemple,dc=com';
$config['password_ldap_searchDN'] = 'cn=roundcube,ou=services,dc=example,dc=com';
$config['password_ldap_searchPW'] = 'secret';
$config['password_ldap_search_base'] = 'ou=people,dc=example,dc=com';
$config['password_ldap_search_filter'] = '(uid=%login)';
$config['password_ldap_encodage'] = 'crypt';
$config['password_ldap_pwattr'] = 'userPassword';
$config['password_ldap_force_replace'] = true;
$config['password_ldap_lchattr'] = '';
$config['password_ldap_samba_pwattr'] = '';
$config['password_ldap_samba_lchattr'] = '';
$config['password_directadmin_host'] = 'tcp://localhost';
$config['password_directadmin_port'] = 2222;
$config['password_vpopmaild_host'] = 'localhost';
$config['password_vpopmaild_port'] = 89;
$config['password_vpopmaild_timeout'] = 10;
$config['password_cpanel_host'] = 'host.domain.com';
$config['password_cpanel_username'] = 'username';
$config['password_cpanel_password'] = 'password';
$config['password_cpanel_port'] = 2087;
$config['password_ximss_host'] = 'mail.example.com';
$config['password_ximss_port'] = 11024;
$config['password_chpasswd_cmd'] = 'sudo /usr/sbin/chpasswd 2> /dev/null';
$config['xmail_host'] = 'localhost';
$config['xmail_user'] = 'YourXmailControlUser';
$config['xmail_pass'] = 'YourXmailControlPass';
$config['xmail_port'] = 6017;
$config['hmailserver_remote_dcom'] = false;
$config['hmailserver_server'] = array(
    'Server'   => 'localhost',      // hostname or ip address
    'Username' => 'administrator',  // windows username
    'Password' => 'password'        // windows user password
);
$config['password_virtualmin_format'] = 0;
$config['password_pw_usermod_cmd'] = 'sudo /usr/sbin/pw usermod -h 0 -n';
$config['password_dbmail_args'] = '-p sha512';
$config['password_expect_bin'] = '/usr/bin/expect';
$config['password_expect_script'] = '';
$config['password_expect_params'] = '';
$config['password_smb_host'] = 'localhost';
$config['password_smb_cmd'] = '/usr/bin/smbpasswd';
$config['password_gearman_host'] = 'localhost';
$config['password_plesk_host'] = '10.0.0.5';
$config['password_plesk_user'] = 'admin';
$config['password_plesk_pass'] = 'password';
$config['password_plesk_rpc_port'] = '8443';
$config['password_plesk_rpc_path'] = 'enterprise/control/agent.php';
$config['password_kpasswd_cmd'] = '/usr/bin/kpasswd';
