name: Publish Docker images

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare environment
        run: |
          cp .env.dist .env

      - name: Build and push images
        run: |
          make build
          .ci/bin/push_image_version.sh ${{ github.event.release.tag_name }}
