name: Test Kubernetes deployment
on:
  pull_request:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kustomize build
        run: |
          make .env
          kustomize build .
  test:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: kind
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
      - name: Setup Kind
        uses: helm/kind-action@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
      - name: Prepare environment
        run: |
          make .env
          cat .github/test-matrix/kubernetes.env >> .env
      - name: Output environment
        run: cat .env
      - name: Pull and build images
        run: |
          export BUILDX_BUILDER=${{ steps.buildx.outputs.name }}
          make build
      - name: Use kubectl context
        run: |
          kind get clusters
          kubectl config use-context kind-${{ env.CLUSTER_NAME }}
      - name: Import images to Kind
        run: |
          kind load docker-image jeboehm/mailserver-mda:latest
          kind load docker-image jeboehm/mailserver-mta:latest
          kind load docker-image jeboehm/mailserver-filter:latest
          kind load docker-image jeboehm/mailserver-web:latest
          kind load docker-image jeboehm/mailserver-unbound:latest
      - name: Prepare tls certs
        run: |
          make-ssl-cert generate-default-snakeoil
          kubectl create secret tls tls-certs --cert=/etc/ssl/certs/ssl-cert-snakeoil.pem --key=/etc/ssl/private/ssl-cert-snakeoil.key
      - name: Start mysql in Kind network
        run: |
          docker run -d --name db --network kind --env-file .env \
            -v ./target/db/rootfs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro \
            --env-file .env \
            mysql:lts
      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -k .
      - name: Check if all resources are deployed
        run: |
          kubectl wait --timeout=5m --for=condition=ready pod -l app.kubernetes.io/name=docker-mailserver
      - name: Get pod status on failure
        if: failure()
        run: |
          kubectl get pods -o wide
          kubectl logs --ignore-errors -l app.kubernetes.io/component=fetchmail
          kubectl logs --ignore-errors -l app.kubernetes.io/component=filter
          kubectl logs --ignore-errors -l app.kubernetes.io/component=mda
          kubectl logs --ignore-errors -l app.kubernetes.io/component=mta
          kubectl logs --ignore-errors -l app.kubernetes.io/component=redis
          kubectl logs --ignore-errors -l app.kubernetes.io/component=unbound
          kubectl logs --ignore-errors -l app.kubernetes.io/component=web
