name: Lint Dockerfiles

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Run linter
        run: |
          make lint-dockerfile
