name: Validate Renovate config
on:
  pull_request:
    paths:
      - renovate.json
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  validate_renovate_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout: |
            renovate.json
          sparse-checkout-cone-mode: false
      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: 24
      - name: Run renovate-config-validator
        run: npx --yes --package renovate -- renovate-config-validator
