name: Sync branch main to next

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync branch main to next
      uses: devmasx/merge-branch@1.4.0
      with:
        from_branch: 'main'
        target_branch: 'next'
        type: now
        github_token: ${{ secrets.GITHUB_TOKEN }}
