apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail
resources:
  - https://github.com/jeboehm/docker-mailserver/deploy/kustomize/?ref=main
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - config.yaml
  - ingress.yaml
patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: longhorn
